# Generated by GitHub Copilot on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialaccount", "0001_initial"),
        ("identity_providers", "0004_alter_identityprovidercategorymapping_map_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issuer_url", models.URLField(blank=True, help_text="OIDC issuer URL", null=True)),
                ("uid", models.CharField(default="sub", help_text="Unique user identifier claim", max_length=100)),
                ("name", models.CharField(blank=True, help_text="Display name claim", max_length=100, null=True)),
                ("email", models.CharField(blank=True, help_text="Email claim", max_length=100, null=True)),
                ("groups", models.CharField(blank=True, help_text="Groups claim", max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, help_text="First name claim", max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, help_text="Last name claim", max_length=100, null=True)),
                ("role", models.CharField(blank=True, help_text="Role claim", max_length=100, null=True)),
                ("verified_email", models.BooleanField(default=False, help_text="Mark email as verified")),
                ("remove_from_groups", models.BooleanField(default=False, help_text="Automatically remove from groups")),
                ("save_oidc_response_logs", models.BooleanField(default=True)),
                (
                    "social_app",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="oidc_configurations", to="socialaccount.socialapp"),
                ),
            ],
            options={
                "verbose_name": "OIDC Configuration",
                "verbose_name_plural": "OIDC Configurations",
                "unique_together": {("social_app", "issuer_url")},
            },
        ),
    ]
